### ISSUE TITLE
Error installing CWS Start pakage

### ISSUE THREAD

**Issue by itmediastudio** [warrenbuckley/CWS-Start#8]
Since the package is 5 Mb I had to increase the  maxRequestLength="" above 4024.  and then was able to load the installer.  After get the package to the point of accepting the install agreement.  I receive the attached error.  This is running on a Win 64 2008 R2 and Umbraco 6.1.3. This 

![cws_start_error](https://f.cloud.github.com/assets/4960431/907694/1e924c98-fd56-11e2-970b-3e460a978164.png)

**Comment by itmediastudio** [comment]
Also why is there an additional zip in the package

**Comment by warrenbuckley** [comment]
In regards to your YSOD, this is because the DLLs are compiled against .NET 4.5 as opposed to .NET 4. Please can you check you have .NET 4.5 installed please and then report back.

In regards to the additional zip the current package packages up any file in the /media folder hence the additional zip/s

Thanks,
Warren

**Comment by itmediastudio** [comment]
That fixed it

**Comment by warrenbuckley** [comment]
Closing this as more an environment issue rather than CWS Start
